import App from "./admin/App";
import SessionWrapper from "./component/sessionWrapper";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OPUS GLOBAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={inter.className}>
          <div className="">
            <App>{children}</App>
          </div>
        </body>
      </SessionWrapper>
    </html>
  );
}
